webapps/urls.py
from django.contrib import admin
from django.urls import path
import maps.views as map_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    
    # webapp pages:
    path('', map_views.home, name="home"),
    path('floor/<int:floor_id>', map_views.floor, name="floor"),
    path('profile', map_views.profile, name="profile"),

    # authentication:
    # have log in and logout handled by the default django things... 
    path('login', auth_views.LoginView.as_view(template_name="maps/login.html"), name="login"), 
    path('logout', map_views.logout_user, name="logout"),

    path('sign-up', map_views.sign_up, name="sign-up"),
    path('password-reset', map_views.home, name="password_reset"),

    # endpoints: 
    path('get_maps_script', map_views.get_maps_script),
    path('get_map_pins', map_views.get_map_pins),

    path('update_navigation_directions', map_views.update_navigation_directions, name="update-navigation"),
    # remove these two endpoints
    path('update_user_location', map_views.update_user_location), 
    path('get_user_location', map_views.get_user_location),
    
]

maps/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.PROTECT, related_name="profile")

    name            = models.CharField(max_length=100) # name of the user's profile :). 
    tag_id          = models.CharField(max_length=200) # Effectively holds the ID of the tag (key of the tag)

    def __str__(self):
        return f"{self.name}"

# Model for classes
class Location(models.Model):

    # name
    name = models.CharField(max_length=100)

    # latitude and longitude of the location
    lat = models.FloatField()
    lng = models.FloatField()

    def __str__(self):
        return f"{self.name}"


# Model for each floor that belongs to each location
class Floor(models.Model):
    # corresponding location 
    location = models.ForeignKey(
        Location, 
        on_delete=models.CASCADE,
        related_name="floors"
    )

    # floor name
    name = models.CharField(max_length=100)

    # image path
    img_path = models.CharField(max_length=100)

    # graph path
    graph_path = models.CharField(max_length=100)

    # Include some information regarding the scale and offset for mapping
    # e.g. full width of map is ~300 pixels wide across the image
    x_pixel_scale = models.IntegerField(default=300)
    y_pixel_scale = models.IntegerField(default=300)

    # this ideally points to the top left corner of where mapping starts
    x_pixel_offset = models.IntegerField(default=0)
    y_pixel_offset = models.IntegerField(default=0)

    # pixel_scale to use for distance remaining estimations. 
    y_pixels_per_meter = models.FloatField(default=10)
    x_pixels_per_meter = models.FloatField(default=10)

    def __str__(self):
        return f"{self.location.name} {self.name}"


class Room(models.Model):
    # corresponding Floor
    floor = models.ForeignKey(
        Floor,
        on_delete=models.CASCADE,
        related_name="rooms",
    )

    # room number
    name = models.CharField(max_length=100)

    x_pos = models.IntegerField()
    y_pos = models.IntegerField()

    # oyes XD
    def __str__(self):
        return f"{self.floor.location.name} {self.floor.name} {self.name}"
    
    
# a model for each of the "tags" made. This will simply be a way of providing
# the user's location to the server. 
class Tag(models.Model):
    id = models.CharField(max_length=100, primary_key=True)

    # x_pos = models.FloatField(null=True, blank=True)
    # y_pos = models.FloatField(null=True, blank=True)

    # rotation = models.FloatField(null=True, blank=True)

    # floor = models.ForeignKey(
    #     Floor,
    #     on_delete=models.CASCADE,
    #     related_name="tags",
    #     null=True
    # )

    # last_update_time = models.FloatField(null=True, blank=True)

maps/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

# Kind of like a modelform? but it would need to inherit both a User class
# and the Profile class, which is weird, so let's leave it hanging in the air.
class SpecialUserCreationForm(UserCreationForm):
    name = forms.CharField(max_length=100, required=True)
    tag_id = forms.CharField(max_length=200, required=False, help_text="Optional")

    def save(self, commit=True):
        if not commit:
            raise NotImplementedError("cannot do this")
        
        # call the parent 
        user = super(UserCreationForm, self).save(commit=True)

        profile = Profile(user=user, 
                          name=self.cleaned_data['name'],
                          tag_id=self.cleaned_data['tag_id'],
                          )
        profile.save()
        return user, profile
    

class ProfileEditForm(forms.Form):
    name = forms.CharField(max_length=100)
    tag_id = forms.CharField(max_length=200)

maps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt 
from django.urls import reverse
from .models import *
from .a_star_alg import navigation_directions
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import SpecialUserCreationForm, ProfileEditForm

import time
import requests
from configparser import ConfigParser

################################################################################
# HTML views
################################################################################

# Home View displaying a map
@login_required
def home(request):
    return render(request, "maps/home.html")


# Floor View displaying a floor of a building. 
@login_required
def floor(request, floor_id):
    context = dict()
    user_profile = request.user.profile

    if ((not user_profile.tag_id) or (len(user_profile.tag_id) < 2)):
        return redirect(profile)

    floor = Floor.objects.get(id=floor_id)

    context["img_file"] = floor.img_path
    context["floorId"] = floor_id
    context["tagId"] = "http_test" # should be connected to user acc
                                    # or for testing, the floor, 
    
    # include the rooms of the floor. 
    context["rooms"] = floor.rooms.all().order_by('name')

    # used for the client to hold information regarding the floor to display
    # the user's position. 
    context["floorScaling"] = {
        "x_scaling": floor.x_pixel_scale,
        "y_scaling": floor.y_pixel_scale,
        "x_offset": floor.x_pixel_offset,
        "y_offset": floor.y_pixel_offset,

        "y_pixels_per_meter": floor.y_pixels_per_meter,
        "x_pixels_per_meter": floor.x_pixels_per_meter,
    }

    return render(request, "maps/floor.html", context=context)


# profile view
@login_required
def profile(request):
    user = request.user
    profile = user.profile

    prof_form = ProfileEditForm(initial={
        "name": profile.name,
        "tag_id": profile.tag_id,
    })

    if (request.method == "POST"):
        form = ProfileEditForm(request.POST)
        if (form.is_valid()):

            profile.name = form.cleaned_data["name"]
            profile.tag_id = form.cleaned_data["tag_id"]
            profile.save()
            prof_form = ProfileEditForm(initial={
                "name": profile.name,
                "tag_id": profile.tag_id,
            })
        else:
            prof_form = form;

    context = {
        "user": user,
        "profile": profile,
        "form": prof_form,
        "tag_id_wrong": (not profile.tag_id) or (len(profile.tag_id) < 2)
    }
    return render(request, "maps/profile.html", context=context)


# sign up
def sign_up(request):
    if (request.method == "POST"):
        form = SpecialUserCreationForm(request.POST)
        if (form.is_valid()):
            # create the user
            user, profile = form.save()

            # create the associated profile
            # profile = Profile(user=user, 
            #                   tag_id="")
            login(request=request, user=user)
            return redirect(home)
        else:
            return render(request, "maps/sign_up.html", context={
                "form": form,
                "next": reverse("home"),
            })
    return render(request, "maps/sign_up.html", context={
        "form": SpecialUserCreationForm(),
        "next": reverse("home"),
    })

def logout_user(request):
    logout(request)
    return redirect(home)

################################################################################
# Asynchronous points
################################################################################

# Proxy point to load the google maps API from the server. 
def get_maps_script(request):
    CONFIG = ConfigParser()
    CONFIG.read("config.ini")

    google_maps_api_key = CONFIG.get("Maps", "Key")

    maps_url = f'https://maps.googleapis.com/maps/api/js?key={google_maps_api_key}&callback=initMap'
    response = requests.get(maps_url)

    # Important: Ensure proper content type for JavaScript
    return HttpResponse(response.content, content_type="application/javascript") 


# AJAX point to get the map pin locations from the server. 
# Let the client build the HTML necessary. 
def get_map_pins(request):

    info = []
    for location in Location.objects.all():
        i = dict()

        i["name"] = location.name
        i["lat"] = location.lat
        i["lng"] = location.lng

        floors = []
        for floor in location.floors.all():
            f = dict()
            f["name"] = floor.name
            f["img_path"] = reverse("floor", args=[floor.id])
            floors.append(f)
        i["floors"] = floors

        info.append(i)
    
    return JsonResponse(info, safe=False, content_type="application/javascript")

"""
Given the position of a user, provide the directions necessary to get to a room

The client will provide these directions as a pixel location.
To use them in our graph, we will convert them into the graph's row and col. 
"""
# import os
def update_navigation_directions(request):
    time_0 = time.time()
    if request.method != 'POST':
        return JsonResponse({'error': "only post requests allowed"})
    
    data = request.POST
    # print(data)

    # print(os.listdir())
    floor = Floor.objects.get(id = data["floor_id"])

    room = floor.rooms.get(name = data["room_name"])
    # room = Room.objects.get(name = data["room_name"])
    # floor = room.floor
    

    graph_path = f"./maps/static/maps/{floor.graph_path}"

    user_row = int(float(data["user_y"]))
    user_col = int(float(data["user_x"]))

    dest_row = room.y_pos
    dest_col = room.x_pos

    paths, txt, icon = navigation_directions(graph_path, user_row, user_col, dest_row, dest_col)
    
    time_1 = time.time()
    print(f"time_taken({time_1-time_0})")
    print(paths, txt)

    return JsonResponse({
        'directions': paths,
        'instruction': txt,
        'icon': icon,
    })

"""
Update the user location for a "floor". 
"""
@csrf_exempt
def update_user_location(request):
    if request.method == 'POST':
        data = request.POST
        # print(data)

        try:
            tag = Tag.objects.get(id=data["id"])
            # print("tag found")
        except:
            tag = Tag.objects.create(id=data["id"])
            print("created new tag")
        
        tag.x_pos = data["x_pos"]
        tag.y_pos = data["y_pos"]
        tag.rotation = data["rotation"]

        tag.floor = Floor.objects.get(id=data["floor"])

        tag.last_update_time = data["time"]

        tag.save()
        return JsonResponse({'message': 'Data received!'})
    else:
        return JsonResponse({'error': 'Only POST requests allowed.'})


USER_TAG = "http_test"
"""
For the "TEST
"""
def get_user_location(request):
    try:
        tag = Tag.objects.get(id=USER_TAG)
    except:
        return JsonResponse({'error': 'Tag ID not found.'})

    return JsonResponse({
        'x_pos': tag.x_pos,
        'y_pos': tag.y_pos,
        'rotation': tag.rotation,
        'time': tag.last_update_time,
    })

maps/templates/maps/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Planner App{% endblock %}</title>

        <!-- Bootstrap5 -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        <link rel="stylesheet" href="/static/maps/default.css">


        <!-- favicon -->
        <!-- <link rel="icon" type="image/x-icon" href="/static/freefood/ui/favicon.ico" > -->

        <!-- JQuerry -->
        <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

        <!-- Bootstrap Icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        
        {% block scripts %}{% endblock %}
    </head>

    <header>
        {% block header %}
        {% endblock %}
    </header>


    <body>        
        {% block body %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>

</html>

maps/templates/maps/floor.html
{% extends "maps/base.html" %}

{% block title %}Floor{% endblock %}

{% block scripts %}
<script src="../../static/maps/floor.js"></script>
<link rel="stylesheet" href="../../static/maps/floor.css">
{% endblock %}

{% block header %}
{% include "maps/subtemplates/header.html" %}
{% endblock %}


{% block body %}

{{ floorId|json_script:"floor-id" }}
{{ tagId|json_script:"tag-id"}}

{{ floorScaling|json_script:"floor-scaling" }}

<div id="mapContainer">

    <!-- hover bubble for navigation directions -->
    <div class="card floorHeader" id="navigation-view" style="display:none">
        <div class="card-body">
            
            <div class="row">
                <div class="col-2 turn-indicator">
                    <span id="turn-direction-icon">
                        <i class="bi bi-sign-turn-left"></i>
                    </span>
                </div>
                <div class="col-10">
                    <div class="row">
                        <span id="turn-direction-text" class="navigation-font">Turn Left</span>
                    </div>
                    <div class="row">
                        <div>
                            <span id="turn-direction-distance">100</span>
                            <span id="turn-direction-distance-units">meters</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- hover bubble for navigation information -->
    <div class="card floorFooter" id="navigation-info" style="display:none">
        <div class="card-body">
            <div class="row">
                <!-- ETA in minutes + Distance in meters -->
                <div class="col-8">
                    <div class="row">
                        <div class="navigation-font">
                            <span id="navigation-time-remaining"></span>
                            <span id="navigation-time-remaining-units">min</span>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <span id="navigation-distance-remaining">2000</span>
                            <span id="navigation-distance-remaining-units">meters</span>
                        </div>
                    </div>
                </div>
                <!-- Buttons for Leaving the view -->
                <div class="col exit-navigation">
                    <button type="button" class="btn btn-danger" id="exit-navigation-button">Exit</button>
                </div>
            </div>
        </div>
    </div>

    <!-- header for inputting location  -->
    <div class="card floorHeader" id="location-select">
        <div id="error"></div>

        <div class="card-body">

            <form method="POST" action="{% url 'update-navigation' %}" id="form">
                {% csrf_token %}

                <label for="roomInput" class="form-label">Enter Location</label>
                
                <div class="input-group">
                    <input class="form-control" list="datalistOptions" id="roomInput" placeholder="Type to search...">
                    <datalist id="datalistOptions">
                        {% for room in rooms %}
                            <option value="{{ room.name }}">
                        {% endfor %}
                    </datalist>
                    <button class="btn btn-outline-secondary" type="submit" id="formSubmit">Go</button>
                </div>
            </form>
        </div>
    </div>

    

    <div id="loadingScreen">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
            <span style="color: white">Trying to connect</span>
        </div>
    </div>

    <!-- floor image background -->
    <img src="../../static/maps/{{ img_file }}" id="floorImg">
    
    <!-- hold the triangle for user position -->
    <div id="userPos"></div>

    <!-- hold the paths the user needs to travel -->
    <canvas id="userPaths"width="100" height="100"></canvas>
        
    </div>
</div>


{% endblock %}

maps/templates/maps/floor_old.html
{% extends "maps/base.html" %}

{% block title %}Floor{% endblock %}

{% block scripts %}
<!-- Jquery UI and a library to help allow draggable objects on mobile device -->
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js" integrity="sha512-0bEtK0USNd96MnO4XhH8jhv3nyRF0eK87pJke6pkYf3cM0uDIhNJy9ltuzqgypoIFXw3JSuiy04tVk4AjpZdZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}

{% block header %}
{% include "maps/subtemplates/header.html" %}
{% endblock %}


{% block body %}
<div class="container-fluid map-container">
    <img src="../../static/maps/{{ img_file }}"  id="draggableImg">
    <div class="clickable-area" id="clickableArea"></div>
</div>



<script>
    $(function() {
      $("#draggableImg").draggable();
    });
    
</script>


{% endblock %}

maps/templates/maps/home.html
{% extends "maps/base.html" %}

{% block title %}Scotty Maps{% endblock %}

{% block scripts %}
<script src="../../static/maps/home.js"></script>
<link rel="stylesheet" href="../../static/maps/home.css">
{% endblock %}

{% block header %}
{% include "maps/subtemplates/header.html" %}
{% endblock %}


{% block body %}

  <div id="map"></div>

{% endblock %}

maps/templates/maps/login.html
{% extends "maps/base.html" %}

{% block title %}Login{% endblock %}

{% block header %}
{% include "maps/subtemplates/header.html" with hide_navbar=True  %}
{% endblock %}

{% block body %}

{% load widget_tweaks %}

<div class="container-sm">
    

    <form method="post" class="m-3" action="{% url 'login' %}">
    {% csrf_token %}
        <div class="mb-3 row">
            <label class="form-label" for="id_username">{{ form.username.label_tag }}</label>
            {% render_field form.username class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.username %}
        </div>

        <div class="mb-3 row">
            <label class="form-label" for="id_password">{{ form.password.label_tag }}</label>
            {% render_field form.password class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.password %}
        </div>

        {% if form.errors %}
            <div>
                <small class="form-text text-danger">
                    Your username and password didn't match. Please try again.
                </small>
            </div>
        {% endif %}
        <div class="d-grid gap-2">
            <button class="btn btn-success" type="submit" value="login">Login</button>
        </div>
        <input type="hidden" name="next" value="{{ next }}">
    </form>

    {# Assumes you set up the password_reset view in your URLconf #}
    <p><a href="{% url 'sign-up' %}">Make an Account</a></p>
</div>

{% endblock %}

maps/templates/maps/profile.html
{% extends "maps/base.html" %}

{% block title %}Profile{% endblock %}

{% block scripts %}
<script>
    function toggleOn() {
        $("#id_name").removeAttr("readonly");
        $("#id_name").removeAttr("disabled");
        $("#id_tag_id").removeAttr("readonly");
        $("#id_tag_id").removeAttr("disabled");

        $("#toggleOnBtn").addClass("hidden");
        $("#submitBtn").removeClass("hidden");
    }
</script>
{% endblock %}

{% block header %}
{% include "maps/subtemplates/header.html" with page="profile" %}
{% endblock %}

{% load widget_tweaks %}

{% block body %}
<div class="container-sm">
    <div class="my-3">
        <div>
            Hello {{ profile.name }}!
        </div>
        <div>
            <a href="{% url 'logout' %}" class="btn btn-danger">Sign Out</a>
        </div>
    </div>

    <form class="m-3" method="post" action="{% url 'profile' %}">
        {% csrf_token %}

        <div class="mb-3 row">
            <label class="form-label" for="id_name">{{ form.name.label_tag }}</label>
            {% render_field form.name|append_attr:"readonly disabled" class="form-control"  %}
            {% include "maps/subtemplates/form_field.html" with field=form.name %}
        </div>

        <div class="mb-3 row">
            <label class="form-label" for="id_tag_id">{{ form.tag_id.label_tag }}</label>
            {% render_field form.tag_id|append_attr:"readonly disabled" class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.tag_id %}
            {% if tag_id_wrong %}
                <small class="form-text text-danger">The tag ID is invalid.</small>
            {% endif %}
        </div>

        <button id="toggleOnBtn" class="btn btn-primary" type="button" onclick="toggleOn();">Edit</button>
        <button id="submitBtn" class="btn btn-success hidden" type="submit" >Submit</button>
    </form>

</div>

{% endblock %}

maps/templates/maps/sign_up.html
{% extends "maps/base.html" %}

{% block title %}Sign Up{% endblock %}

{% block header%}
{% include "maps/subtemplates/header.html" with hide_navbar=True %}
{% endblock %}

{% block body %}

{% load widget_tweaks %}

<div class="container-sm">


    <form method="post" class="m-3" action="{% url 'sign-up' %}">
        {% csrf_token %}

        <div class="mb-3 row">
            <label class="form-label" for="id_username">{{ form.username.label_tag }}</label>
            {% render_field form.username class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.username %}
        </div>

        <div class="mb-3 row">
            <label class="form-label" for="id_name">{{ form.name.label_tag }}</label>
            {% render_field form.name class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.name %}
        </div>

        <div class="mb-3 row">
            <label class="form-label" for="id_tag_id">{{ form.tag_id.label_tag }}</label>
            {% render_field form.tag_id class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.tag_id %}
        </div>

        <div class="mb-3 row">
            <label class="form-label" for="id_password1">{{ form.password1.label_tag }}</label>
            {% render_field form.password1 class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.password1 %}
        </div>

        <div class="mb-3 row" for="id_password2">
            <label class="form-label">{{ form.password2.label_tag }}</label>
            {% render_field form.password2 class="form-control" %}
            {% include "maps/subtemplates/form_field.html" with field=form.password2 %}
        </div>

        <div class="d-grid gap-2">
            <button class="btn btn-success" type="submit" value="login">Make Account</button>
        </div>

    </form>
</div>

{% endblock %}